package Pojos;
// Generated 10-22-2015 07:12:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private String codCurso;
     private Docente docente;
     private Supervisor supervisor;
     private String nombre;
     private Integer duracion;
     private Double precio;
     private Set detallecursoses = new HashSet(0);

    public Curso() {
    }

	
    public Curso(String codCurso) {
        this.codCurso = codCurso;
    }
    public Curso(String codCurso, Docente docente, Supervisor supervisor, String nombre, Integer duracion, Double precio, Set detallecursoses) {
       this.codCurso = codCurso;
       this.docente = docente;
       this.supervisor = supervisor;
       this.nombre = nombre;
       this.duracion = duracion;
       this.precio = precio;
       this.detallecursoses = detallecursoses;
    }
   
    public String getCodCurso() {
        return this.codCurso;
    }
    
    public void setCodCurso(String codCurso) {
        this.codCurso = codCurso;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public Supervisor getSupervisor() {
        return this.supervisor;
    }
    
    public void setSupervisor(Supervisor supervisor) {
        this.supervisor = supervisor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(Integer duracion) {
        this.duracion = duracion;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Set getDetallecursoses() {
        return this.detallecursoses;
    }
    
    public void setDetallecursoses(Set detallecursoses) {
        this.detallecursoses = detallecursoses;
    }




}


