package Pojos;
// Generated 10-22-2015 07:12:10 PM by Hibernate Tools 4.3.1



/**
 * Detallecursos generated by hbm2java
 */
public class Detallecursos  implements java.io.Serializable {


     private DetallecursosId id;
     private Cliente cliente;
     private Curso curso;

    public Detallecursos() {
    }

	
    public Detallecursos(DetallecursosId id) {
        this.id = id;
    }
    public Detallecursos(DetallecursosId id, Cliente cliente, Curso curso) {
       this.id = id;
       this.cliente = cliente;
       this.curso = curso;
    }
   
    public DetallecursosId getId() {
        return this.id;
    }
    
    public void setId(DetallecursosId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }




}


