package Pojos;
// Generated 10-22-2015 07:12:10 PM by Hibernate Tools 4.3.1



/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private String codOferta;
     private Double precio;

    public Oferta() {
    }

	
    public Oferta(String codOferta) {
        this.codOferta = codOferta;
    }
    public Oferta(String codOferta, Double precio) {
       this.codOferta = codOferta;
       this.precio = precio;
    }
   
    public String getCodOferta() {
        return this.codOferta;
    }
    
    public void setCodOferta(String codOferta) {
        this.codOferta = codOferta;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }




}


