package Pojos;
// Generated 10-22-2015 07:12:10 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor  implements java.io.Serializable {


     private String idSupervisor;
     private String nombre;
     private String apellido;
     private String correo;
     private Set cursos = new HashSet(0);

    public Supervisor() {
    }

	
    public Supervisor(String idSupervisor) {
        this.idSupervisor = idSupervisor;
    }
    public Supervisor(String idSupervisor, String nombre, String apellido, String correo, Set cursos) {
       this.idSupervisor = idSupervisor;
       this.nombre = nombre;
       this.apellido = apellido;
       this.correo = correo;
       this.cursos = cursos;
    }
   
    public String getIdSupervisor() {
        return this.idSupervisor;
    }
    
    public void setIdSupervisor(String idSupervisor) {
        this.idSupervisor = idSupervisor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getCursos() {
        return this.cursos;
    }
    
    public void setCursos(Set cursos) {
        this.cursos = cursos;
    }




}


